build: false

environment:
  matrix:
  MINICONDA: "C:\\Miniconda3-x64"
    - PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      NUMPY_VERSION: "1.13.1"
      SCIPY_VERSION: "0.19.1"
      SKLEARN_VERSION: "0.19.1"

    - PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      NUMPY_VERSION: "*"
      SCIPY_VERSION: "*"
      SKLEARN_VERSION: "*"

install:
  # Prepend miniconda installed Python to the PATH of this build
  # Add Library/bin directory to fix issue
  # https://github.com/conda/conda/issues/1753
  - cmd: call %MINICONDA%\Scripts\activate.bat
  # install the dependencies
  - conda create -n test-env --yes -c conda-forge python=%PYTHON_VERSION% numpy==%NUMPY_VERSION% scipy==%SCIPY_VERSION% scikit-learn==%SKLEARN_VERSION% codecov nose pytest pytest-cov
  - conda activate test-env
  - pip install .
  - python --version

test_script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=skltemplate --pyargs skltemplate

after_test:
  - cp .coverage %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - codecov
